services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - luma_postgres:/var/lib/postgresql/data

volumes:
  luma_postgres:
    driver: local